//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Resources {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplication2.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Koordinat değeri geçerli aralıkta değil. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CoordinateOutOfRange {
            get {
                return ResourceManager.GetString("CoordinateOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bir hata oluştu. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string GenericError {
            get {
                return ResourceManager.GetString("GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Intersection kontrolü tamamlandı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string IntersectionControlCompleted {
            get {
                return ResourceManager.GetString("IntersectionControlCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Geçersiz koordinat değerleri tespit edildi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string InvalidCoordinates {
            get {
                return ResourceManager.GetString("InvalidCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Geçersiz çizgi geometrisi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string InvalidLineFormat {
            get {
                return ResourceManager.GetString("InvalidLineFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Geçersiz poligon geometrisi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string InvalidPolygonFormat {
            get {
                return ResourceManager.GetString("InvalidPolygonFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Geometrik veri okunamadı. WKT formatını kontrol edin. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string InvalidWktFormat {
            get {
                return ResourceManager.GetString("InvalidWktFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enlem değeri -90 ile 90 arasında olmalıdır. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LatitudeOutOfRange {
            get {
                return ResourceManager.GetString("LatitudeOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Çizgi başarılı bir şekilde eklendi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LineAdded {
            get {
                return ResourceManager.GetString("LineAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Çizgi silinemedi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LineCouldNotBeDeleted {
            get {
                return ResourceManager.GetString("LineCouldNotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Çizgi başarılı bir şekilde silindi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LineDeleted {
            get {
                return ResourceManager.GetString("LineDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Çizgi başarılı bir şekilde bulundu. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LineFound {
            get {
                return ResourceManager.GetString("LineFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Çizgi bulunamadı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LineNotFound {
            get {
                return ResourceManager.GetString("LineNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Silinecek çizgi bulunamadı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LineNotFoundForDelete {
            get {
                return ResourceManager.GetString("LineNotFoundForDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Güncellenecek çizgi bulunamadı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LineNotFoundForUpdate {
            get {
                return ResourceManager.GetString("LineNotFoundForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Çizgi başarılı bir şekilde güncellendi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LineUpdated {
            get {
                return ResourceManager.GetString("LineUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Boylam değeri -180 ile 180 arasında olmalıdır. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LongitudeOutOfRange {
            get {
                return ResourceManager.GetString("LongitudeOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şehir adı &apos;ğ&apos; harfiyle başlayamaz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NameCannotStartsWithGh {
            get {
                return ResourceManager.GetString("NameCannotStartsWithGh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şehir adı büyük harfle başlamalıdır. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NameMustStartWithUppercase {
            get {
                return ResourceManager.GetString("NameMustStartWithUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şehir adı boş bırakılamaz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nokta başarıyla eklendi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PointAdded {
            get {
                return ResourceManager.GetString("PointAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nokta silinemedi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PointCouldNotBeDeleted {
            get {
                return ResourceManager.GetString("PointCouldNotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nokta başarılı bir şekilde silindi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PointDeleted {
            get {
                return ResourceManager.GetString("PointDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nokta başarılı bir şekilde bulundu. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PointFound {
            get {
                return ResourceManager.GetString("PointFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nokta bulunamadı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PointNotFound {
            get {
                return ResourceManager.GetString("PointNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Silinecek nokta bulunamadı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PointNotFoundForDelete {
            get {
                return ResourceManager.GetString("PointNotFoundForDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Güncellenecek nokta bulunamadı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PointNotFoundForUpdate {
            get {
                return ResourceManager.GetString("PointNotFoundForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nokta başarılı bir şekilde güncellendi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PointUpdated {
            get {
                return ResourceManager.GetString("PointUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Poligon başarılı bir şekilde eklendi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PolygonAdded {
            get {
                return ResourceManager.GetString("PolygonAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Poligon silinemedi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PolygonCouldNotBeDeleted {
            get {
                return ResourceManager.GetString("PolygonCouldNotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Poligon başarılı bir şekilde silindi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PolygonDeleted {
            get {
                return ResourceManager.GetString("PolygonDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Poligon başarılı bir şekilde bulundu. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PolygonFound {
            get {
                return ResourceManager.GetString("PolygonFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Poligon bulunamadı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PolygonNotFound {
            get {
                return ResourceManager.GetString("PolygonNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Silinecek poligon bulunamadı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PolygonNotFoundForDelete {
            get {
                return ResourceManager.GetString("PolygonNotFoundForDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Güncellenecek poligon bulunamadı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PolygonNotFoundForUpdate {
            get {
                return ResourceManager.GetString("PolygonNotFoundForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Poligon başarılı bir şekilde güncellendi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PolygonUpdated {
            get {
                return ResourceManager.GetString("PolygonUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Arama kriterine uygun nokta bulunamadı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SearchNoResults {
            get {
                return ResourceManager.GetString("SearchNoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Arama kriterine uygun {0} nokta bulundu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SearchResultsFound {
            get {
                return ResourceManager.GetString("SearchResultsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Arama çubuğu boş olamaz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SearchTermCannotBeEmpty {
            get {
                return ResourceManager.GetString("SearchTermCannotBeEmpty", resourceCulture);
            }
        }
    }
}
